### ISSUE TITLE
Getting and error while trying to upload s3

### ISSUE THREAD

**Issue by kaankilic** [Metrique/laravel-cdnify#3]
Hi,

I am trying to upload items to s3 but I am getting the following error.
`
Start asset upload to s3.
Encountered an unknown error processing this request, please try again.
`

**Comment by ddziovalas** [comment]
I'm getting the same error.
----
Edit: Laravel 5.4 uses different manifest file name and paths, than default config of this package. So after some experimenting i've managed to solve this problem by editing `config/cdnify.php` file:
`'build_source' => '/'` and `'manifest' => '/mix-manifest.json'`
